name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust as necessary
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t myusername/myapp .

      - name: Run tests
        run: |
          docker run myusername/myapp python -m unittest discover  # Adjust if necessary

      - name: Push Docker image
        run: |
          docker push myusername/myapp
